sudo: required
services:
  - docker

before_install:
  - docker build -t alamidrissitaha/docker-react -f Dockerfile.dev .

script:
  - docker run alamidrissitaha/docker-react npm run test -- --coverage
  
